### ISSUE TITLE
TRACE hangs when running

### ISSUE THREAD

**Issue by codecodebear** [RUC-NLPIR/FlashRAG#71]
Hello, 

When I run TRACE, it hangs after some time. 
This happens after this [commit](https://github.com/RUC-NLPIR/FlashRAG/commit/d7a713685f232174be6cb9cdc3016c18f6f9ddbc), I remembered running TRACE before this commit, but I don't think it hung before.

Below is the log outputted (hangs on the last line). I have waited around 15 minutes, not sure if this isn't enough.
```
Setting num_proc from 4 back to 1 for the train split to disable multiprocessing as it only contains one shard.
Generating train split: 21015324 examples [00:25, 818915.84 examples/s]
Loading dataset shards: 100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 123.44it/s]
Load new generator
INFO 08-07 00:11:39 config.py:715] Defaulting to use mp for distributed inference
INFO 08-07 00:11:39 llm_engine.py:176] Initializing an LLM engine (v0.5.3.post1) with config: model='/workspace/models/Meta-Llama-3-8B-Instruct', speculative_config=None, tokenizer='/workspace/models/Meta-Llama-3-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/workspace/models/Meta-Llama-3-8B-Instruct, use_v2_block_manager=False, enable_prefix_caching=False)
INFO 08-07 00:11:39 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
(VllmWorkerProcess pid=3001) INFO 08-07 00:11:41 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=3002) INFO 08-07 00:11:41 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=3003) INFO 08-07 00:11:41 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=3001) INFO 08-07 00:11:42 utils.py:784] Found nccl from library libnccl.so.2
INFO 08-07 00:11:42 utils.py:784] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=3001) INFO 08-07 00:11:42 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=3002) INFO 08-07 00:11:42 utils.py:784] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=3002) INFO 08-07 00:11:42 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 08-07 00:11:42 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=3003) INFO 08-07 00:11:42 utils.py:784] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=3003) INFO 08-07 00:11:42 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 08-07 00:11:44 custom_all_reduce_utils.py:202] generating GPU P2P access cache in /root/.cache/vllm/gpu_p2p_access_cache_for_0,1,2,3.json
INFO 08-07 00:11:57 custom_all_reduce_utils.py:232] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1,2,3.json
(VllmWorkerProcess pid=3003) INFO 08-07 00:11:57 custom_all_reduce_utils.py:232] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1,2,3.json
(VllmWorkerProcess pid=3001) INFO 08-07 00:11:57 custom_all_reduce_utils.py:232] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1,2,3.json
(VllmWorkerProcess pid=3002) INFO 08-07 00:11:57 custom_all_reduce_utils.py:232] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1,2,3.json
INFO 08-07 00:11:57 shm_broadcast.py:241] vLLM message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1, 2, 3], buffer=<vllm.distributed.device_communicators.shm_broadcast.ShmRingBuffer object at 0x798ed2eaa410>, local_subscribe_port=52691, local_sync_port=44907, remote_subscribe_port=None, remote_sync_port=None)
INFO 08-07 00:11:57 model_runner.py:680] Starting to load model /workspace/models/Meta-Llama-3-8B-Instruct...
(VllmWorkerProcess pid=3002) INFO 08-07 00:11:57 model_runner.py:680] Starting to load model /workspace/models/Meta-Llama-3-8B-Instruct...
(VllmWorkerProcess pid=3003) INFO 08-07 00:11:57 model_runner.py:680] Starting to load model /workspace/models/Meta-Llama-3-8B-Instruct...
(VllmWorkerProcess pid=3001) INFO 08-07 00:11:57 model_runner.py:680] Starting to load model /workspace/models/Meta-Llama-3-8B-Instruct...
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:00,  4.73it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:00<00:00,  4.45it/s]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:00<00:00,  4.27it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:00<00:00,  5.38it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:00<00:00,  4.98it/s]

INFO 08-07 00:11:58 model_runner.py:692] Loading model weights took 3.7417 GB
(VllmWorkerProcess pid=3001) INFO 08-07 00:11:59 model_runner.py:692] Loading model weights took 3.7417 GB
(VllmWorkerProcess pid=3003) INFO 08-07 00:11:59 model_runner.py:692] Loading model weights took 3.7417 GB
(VllmWorkerProcess pid=3002) INFO 08-07 00:11:59 model_runner.py:692] Loading model weights took 3.7417 GB
INFO 08-07 00:12:02 distributed_gpu_executor.py:56] # GPU blocks: 115854, # CPU blocks: 8192
INFO 08-07 00:12:04 model_runner.py:980] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 08-07 00:12:04 model_runner.py:984] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(VllmWorkerProcess pid=3001) INFO 08-07 00:12:04 model_runner.py:980] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=3001) INFO 08-07 00:12:04 model_runner.py:984] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(VllmWorkerProcess pid=3003) INFO 08-07 00:12:04 model_runner.py:980] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=3003) INFO 08-07 00:12:04 model_runner.py:984] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(VllmWorkerProcess pid=3002) INFO 08-07 00:12:05 model_runner.py:980] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=3002) INFO 08-07 00:12:05 model_runner.py:984] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(VllmWorkerProcess pid=3003) INFO 08-07 00:12:12 custom_all_reduce.py:219] Registering 2275 cuda graph addresses
INFO 08-07 00:12:12 custom_all_reduce.py:219] Registering 2275 cuda graph addresses
(VllmWorkerProcess pid=3002) INFO 08-07 00:12:12 custom_all_reduce.py:219] Registering 2275 cuda graph addresses
(VllmWorkerProcess pid=3001) INFO 08-07 00:12:12 custom_all_reduce.py:219] Registering 2275 cuda graph addresses
(VllmWorkerProcess pid=3003) INFO 08-07 00:12:12 model_runner.py:1181] Graph capturing finished in 8 secs.
(VllmWorkerProcess pid=3002) INFO 08-07 00:12:12 model_runner.py:1181] Graph capturing finished in 7 secs.
(VllmWorkerProcess pid=3001) INFO 08-07 00:12:12 model_runner.py:1181] Graph capturing finished in 8 secs.
INFO 08-07 00:12:12 model_runner.py:1181] Graph capturing finished in 8 secs.
INFO 08-07 00:12:13 config.py:715] Defaulting to use mp for distributed inference
INFO 08-07 00:12:13 llm_engine.py:176] Initializing an LLM engine (v0.5.3.post1) with config: model='/workspace/models/Meta-Llama-3-8B-Instruct', speculative_config=None, tokenizer='/workspace/models/Meta-Llama-3-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/workspace/models/Meta-Llama-3-8B-Instruct, use_v2_block_manager=False, enable_prefix_caching=False)
(VllmWorkerProcess pid=3519) INFO 08-07 00:12:15 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=3518) INFO 08-07 00:12:15 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=3517) INFO 08-07 00:12:15 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
```

Below is the log message when I terminate the run:
```
INFO 08-07 08:50:32 multiproc_worker_utils.py:136] Terminating local vLLM worker processes
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/FlashRAG/examples/methods/run_exp.py", line 562, in <module>
[rank0]:     func(args)
[rank0]:   File "/workspace/FlashRAG/examples/methods/run_exp.py", line 484, in trace
[rank0]:     pipeline = SequentialPipeline(config)
[rank0]:   File "/workspace/FlashRAG/flashrag/pipeline/pipeline.py", line 70, in __init__
[rank0]:     self.generator = get_generator(config) if generator is None else generator
[rank0]:   File "/workspace/FlashRAG/flashrag/utils/utils.py", line 33, in get_generator
[rank0]:     return getattr(importlib.import_module("flashrag.generator"), "VLLMGenerator")(config, **params)
[rank0]:   File "/workspace/FlashRAG/flashrag/generator/generator.py", line 194, in __init__
[rank0]:     self.model = LLM(
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 155, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 441, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 251, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 25, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 47, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 123, in _init_executor
[rank0]:     self._run_workers("init_device")
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 182, in _run_workers
[rank0]:     ] + [output.get() for output in worker_outputs]
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 182, in <listcomp>
[rank0]:     ] + [output.get() for output in worker_outputs]
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 58, in get
[rank0]:     raise self.result.exception
[rank0]: ChildProcessError: worker died
```
Can you take a look? Thank you!

**Comment by ignorejjj** [comment]
Thanks for your discovery. The previously modified code resulted in duplicate loading of the generator, maybe caused  the hung. I have fixed it and you can try it now.

**Comment by codecodebear** [comment]
Hi, Thanks for your fix! I met another issue:

```
Retrieval process: 100%|██████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.95it/s]
Begin extracting triples
Processed prompts: 100%|█| 246/246 [00:09<00:00, 25.97it/s, est. speed input: 23553.44 toks/s, output: 4637
Something wrong with this triple: "title", Skip this triple!
Something wrong with this triple: "/title", Skip this triple!
Something wrong with this triple: "title", Skip this triple!
Something wrong with this triple: "/title", Skip this triple!
Something wrong with this triple: "title", Skip this triple!
Something wrong with this triple: "/title", Skip this triple!
Something wrong with this triple: "title", Skip this triple!
Something wrong with this triple: "/title", Skip this triple!
Something wrong with this triple: "title", Skip this triple!
Something wrong with this triple: "/title", Skip this triple!
Something wrong with this triple: "title, Crossover (automobile); first model, AMC Eagle, released in 1979", Skip this triple!
Something wrong with this triple: "Can't Get It Out of My Head; chart performance in the UK", Skip this triple!
Something wrong with this triple: "Known", Skip this triple!
Finish extracting tiples
Begin generating reasoning chain
Generating reasoning chain for query:   0%|                                         | 0/50 [00:00<?, ?it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/FlashRAG/examples/methods/run_exp.py", line 562, in <module>
[rank0]:     func(args)
[rank0]:   File "/workspace/FlashRAG/examples/methods/run_exp.py", line 486, in trace
[rank0]:     result = pipeline.run(test_data)
[rank0]:   File "/workspace/FlashRAG/flashrag/pipeline/pipeline.py", line 103, in run
[rank0]:     refine_results = self.refiner.batch_run(dataset)
[rank0]:   File "/workspace/FlashRAG/flashrag/refiner/kg_refiner.py", line 565, in batch_run
[rank0]:     reasoning_chain_result = self.get_reasoning_chain(all_query, all_doc_triples, triple_to_doc_ids)
[rank0]:   File "/workspace/FlashRAG/flashrag/refiner/kg_refiner.py", line 449, in get_reasoning_chain
[rank0]:     generate_output = self.generator.generate(input_prompts, max_tokens=32, return_dict=True)
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/workspace/FlashRAG/flashrag/generator/generator.py", line 243, in generate
[rank0]:     sampling_params = SamplingParams(**generation_params)
[rank0]: TypeError: SamplingParams.__init__() got an unexpected keyword argument 'return_dict'
```

**Comment by ignorejjj** [comment]
Sorry, due to the output limitation of vllm (unable to return complete logits), we are unable to use vllm as a generator in this method.

**Comment by codecodebear** [comment]
Thank you for pointing it out! I forgot this again.

I have a follow-up question: I tried both ```hf``` and ```fschat``` and saw that they use 4 GPUs at 20% vRAM utilization. So I increased the batch size from ```generator_batch_size: 2``` to ```generator_batch_size: 64```, but this cause ```CUDA OOM``` (32 batch size will not cause CUDA OOM).
I found out that the GPU vRAM utilization is not equal among all GPUs, one GPU's memory is full while other 3's are at 20-50%, which I think if we can **allocate GPU's memory approximately equally among all GPUs**, we can speed up the generating process.
Do you know if there is a solution to this?

Thank you so much!
